[package]
name = "music-now"
version = "0.1.0"
authors = ["LDprg <lukas_4dr@gmx.at>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
dioxus = { version = "0.7.0-rc.0", features = ["router", "fullstack"] }
dioxus-free-icons = { git = "https://github.com/PupsieCo/dioxus-free-icons", features = [
    "hero-icons-solid",
] }
m3u8-rs = { version = "6.0.0" }
regex = { version = "1.11.3" }
reqwest = { version = "0.12.23", default-features = false, features = [
    "charset",
    "http2",
    "json",
    "rustls-tls",
] }
rodio = { version = "0.21.1", features = ["symphonia-all"] }
scraper = { version = "0.24.0" }
serde_json = { version = "1.0.145" }
tokio = { version = "1.47.1", features = [
    "io-util",
    "macros",
    "rt",
    "sync",
    "time",
] }

[features]
default = []
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
