[package]
name = "music-now"
version = "0.1.0"
authors = ["LDprg <lukas_4dr@gmx.at>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
dioxus = { version = "0.7.0-rc.1", features = ["router", "fullstack"] }
dioxus-free-icons = { git = "https://github.com/LDprg/dioxus-free-icons", features = [
    "hero-icons-solid",
] }
m3u8-rs = { version = "6.0.0", optional = true }
regex = { version = "1.12.1", optional = true }
reqwest = { version = "0.12.23", default-features = false, features = [
    "brotli",
    "charset",
    "deflate",
    "gzip",
    "http2",
    "http3",
    "json",
    "rustls-tls",
    "system-proxy",
    "zstd",
] }
scraper = { version = "0.24.0", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", optional = true }
tokio = { version = "1.47.1", features = ["full"], optional = true }
rodio = { git = "https://github.com/RustAudio/rodio", branch = "feat/comprehensive-seeking-and-bit-depth", optional = true }
format_serde_error = "0.3.0"

[features]
default = []
web = ["dioxus/web"] # Development only
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = [
    "dioxus/server",
    "dep:tokio",
    "dep:rodio",
    "dep:scraper",
    "dep:serde_json",
    "dep:m3u8-rs",
    "dep:regex",
]

[profile]

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
