[application]

title = "MusicNow"

[web.app]

# HTML title tag content
title = "MusicNow"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "LDprg"
identifier = "com.ldprg"
icon = ["assets/icon.png"]
